### ISSUE TITLE
AssertionError for empty 'imports' list in CU when 'is_visible' is called during parsing

### ISSUE THREAD

**Issue by markusrosskopf** [bmw-software-engineering/trlc#70] opened 2024-01-31 09:32 UTC
rsl file to reproduce the AssertionError:

```
package Test3
import 

type T {
  x Common.Item
}
```

**Comment by florianschanda** [comment] 2024-05-18 13:35
Can you provide a bit more to reproduce this please? I assume this is API related?

**Comment by markusrosskopf** [comment] 2024-07-16 07:36
Hi @florianschanda, when the method [is_visible](https://github.com/bmw-software-engineering/trlc/blob/d58639c049382052f486293091d622b0ef13dfae/trlc/ast.py#L277) is called while the keyword import is not followed by a name leaving self.imports empty the [assert](https://github.com/bmw-software-engineering/trlc/blob/d58639c049382052f486293091d622b0ef13dfae/trlc/ast.py#L279C16-L279C28) statement is triggered. Shouldn't we print an error here instead?

**Comment by christophkloeffel** [comment] 2024-09-11 11:58
I am not able to reproduce this issue. So I would argue closing this issue

**Closed by christophkloeffel** 2024-09-11 11:58 UTC
